service: wordle-leaderboard
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  stage: live
  httpApi:
    disableDefaultEndpoint: true
    shouldStartNameWithService: true
    cors:
      allowedOrigins:
        - 'https://wordle.kellenanker.com'
        - 'http://wordle.kellenanker.com'
        - 'http://localhost:3000'
      allowedHeaders: '*'
      allowCredentials: false
      maxAge: 300

  tags:
    Serverless: true

  stackTags:
    Serverless: true

  iam:
    role:
      statements:
        - Effect: Allow
          Action: secretsmanager:GetSecretValue
          Resource:
            - Ref: TwilioAuthTokenSecret
            - Ref: TwilioAccountSid
            - Ref: TwilioMessagingServiceSid
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - !GetAtt ScoresTable.Arn
            - !GetAtt WordlesTable.Arn
            - !GetAtt UsersTable.Arn
            - !GetAtt IpUtcOffsetLookupTable.Arn

  environment:
    LOG_LEVEL: DEBUG
    SCORES_TABLE: !Ref ScoresTable
    WORDLES_TABLE: !Ref WordlesTable
    USERS_TABLE: !Ref UsersTable
    IP_UTC_OFFSET_TABLE: !Ref IpUtcOffsetLookupTable
    TWILIO_MESSAGING_SERVICE_SID: !Ref TwilioMessagingServiceSid
    TWILIO_AUTH_TOKEN: !Ref TwilioAuthTokenSecret
    TWILIO_ACCOUNT_SID: !Ref TwilioAccountSid
    TZ_API: https://worldtimeapi.org/api/ip/
    WORDLE_ARCHIVE_API: https://wordfinder.yourdictionary.com/wordle/answers
    DICTIONARY_API: https://api.dictionaryapi.dev/api/v2/entries/en/

package:
  individually: true
  patterns:
    - 'helpers/**'
    - '!node_modules/**'
    - '!package-lock.json'
    - '!package.json'
    - '!poetry.lock'
    - '!pyproject.toml'

functions:
  wordleLeaderboard:
    name: wordle-leaderboard
    handler: main.api_handler
    memorySize: 256
    timeout: 29
    events:
      - schedule:
          name: wordle-answer-updater
          description: Get daily Wordle export
          rate: cron(15 0 * * ? *)
          input:
            updater: "yes"
      - schedule:
          name: wordle-reminder
          description: Remind users to do the Wordle
          rate: cron(0 23 * * ? *)
          input:
            reminder: "yes"
      - httpApi:
          path: '/post'
          method: POST
      - httpApi:
          path: '/leaderboard'
          method: GET
      - httpApi:
          path: '/today'
          method: GET
      - httpApi:
          path: '/wordles'
          method: GET
      - httpApi:
          path: '/wordle/{wordle}'
          method: GET
      - httpApi:
          path: '/users'
          method: GET
      - httpApi:
          path: '/user/{user}'
          method: GET
    layers:
      - Ref: PythonRequirementsLambdaLayer

custom:
  domainName: kellenanker.com
  fqdn: api.wordle.${self:custom.domainName}

  customDomain:
    domainName: ${self:custom.fqdn}
    stage: live
    createRoute53Record: true
    certificateName: ${self:custom.fqdn}
    autoDomain: true
    autoDomainWaitFor: 300
    endpointType: regional
    securityPolicy: tls_1_2
    apiType: http

  customCertificate:
    certificateName: ${self:custom.fqdn}
    hostedZoneNames: ${self:custom.domainName}.

  logRetentionInDays: 7

  pythonRequirements:
    layer: true

plugins:
  - serverless-python-requirements
  - serverless-domain-manager
  - serverless-certificate-creator
  - serverless-plugin-log-retention
  - serverless-plugin-resource-tagging
  - serverless-plugin-git-variables

resources:
  Resources:
    ScoresTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: wordle-leaderboard
        DeletionProtectionEnabled: true
        AttributeDefinitions:
          - AttributeName: PhoneNumber
            AttributeType: N
          - AttributeName: PuzzleNumber
            AttributeType: N
        KeySchema:
          - AttributeName: PhoneNumber
            KeyType: HASH
          - AttributeName: PuzzleNumber
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    WordlesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: wordles
        DeletionProtectionEnabled: true
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: N
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        DeletionProtectionEnabled: true
        AttributeDefinitions:
          - AttributeName: PhoneNumber
            AttributeType: N
        KeySchema:
          - AttributeName: PhoneNumber
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    IpUtcOffsetLookupTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ip-utc-offset-lookup
        DeletionProtectionEnabled: true
        AttributeDefinitions:
          - AttributeName: IpAddress
            AttributeType: S
        KeySchema:
          - AttributeName: IpAddress
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    TwilioAuthTokenSecret:
      Type: AWS::SecretsManager::Secret
      Properties:
        Description: Twilio Auth Token
        Name: twilio/auth-token
    TwilioAccountSid:
      Type: AWS::SecretsManager::Secret
      Properties:
        Description: Twilio Account Sid
        Name: twilio/account-sid
    TwilioMessagingServiceSid:
      Type: AWS::SecretsManager::Secret
      Properties:
        Description: Twilio Messaging Service Sid
        Name: twilio/messaging-service-sid
